#!/usr/bin/env python3
"""
Decision Receipt PoC — verify_receipt.py

This script verifies minimal A-DAP decision receipts generated by generate_receipt.py.

It is intentionally simple and demo-only.

What it verifies:
- Required receipt fields are present.
- decision_hash matches the committed receipt contents.
- demo HMAC signature matches the unsigned receipt payload.
- explanation_hash is treated as fixation, not validation.
- split-view conflicts can be detected between two receipts with the same decision_id.

What it does NOT verify:
- fairness
- legality
- truth
- input correctness
- model validity
- explanation adequacy
- institutional legitimacy
- production-grade signatures
- RFC 3161 timestamps
- public anchoring
"""

from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple


RECEIPT_TYPE = "adap_decision_receipt"

# Must match generate_receipt.py for this PoC.
# Demo-only. Not production security.
DEMO_SIGNING_SECRET = b"demo-only-not-production-secret"


REQUIRED_FIELDS = [
    "receipt_type",
    "receipt_version",
    "receipt_label",
    "issued_at",
    "decision_id",
    "affected_party_ref",
    "policy_ref",
    "model_ref",
    "input_hash",
    "output_hash",
    "explanation_hash",
    "decision_hash",
    "verification_method",
    "limits",
    "signature",
]


COMMITTED_DECISION_FIELDS = [
    "decision_id",
    "affected_party_ref",
    "policy_ref",
    "model_ref",
    "input_hash",
    "output_hash",
    "explanation_hash",
]


def canonical_json(data: Dict[str, Any]) -> str:
    """
    Produce deterministic JSON for hashing.

    This mirrors generate_receipt.py.
    Production systems should use a formal canonicalization scheme
    such as RFC 8785 JSON Canonicalization Scheme where appropriate.
    """
    return json.dumps(
        data,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )


def sha256_text(value: str) -> str:
    """Return sha256 hash of a string with sha256: prefix."""
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()
    return f"sha256:{digest}"


def sha256_json(data: Dict[str, Any]) -> str:
    """Return sha256 hash of deterministic JSON."""
    return sha256_text(canonical_json(data))


def demo_signature(message: str) -> str:
    """
    Return demo HMAC signature.

    This is not production security.
    It exists only for local PoC verification.
    """
    digest = hmac.new(
        DEMO_SIGNING_SECRET,
        message.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()
    return f"demo-hmac-sha256:{digest}"


def load_json(path: Path) -> Dict[str, Any]:
    """Load JSON file."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise ValueError(f"File not found: {path}") from None
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in {path}: {exc}") from None

    if not isinstance(data, dict):
        raise ValueError(f"Receipt must be a JSON object: {path}")

    return data


def unsigned_receipt_payload(receipt: Dict[str, Any]) -> Dict[str, Any]:
    """
    Rebuild the unsigned receipt payload.

    generate_receipt.py signs all fields before adding:
    - signature
    - signature_warning
    """
    return {
        key: value
        for key, value in receipt.items()
        if key not in {"signature", "signature_warning"}
    }


def committed_decision_payload(receipt: Dict[str, Any]) -> Dict[str, Any]:
    """Extract fields that define the committed decision hash."""
    return {field: receipt[field] for field in COMMITTED_DECISION_FIELDS}


def check_required_fields(receipt: Dict[str, Any]) -> List[str]:
    """Return missing required fields."""
    return [field for field in REQUIRED_FIELDS if field not in receipt]


def verify_decision_hash(receipt: Dict[str, Any]) -> Tuple[bool, str, str]:
    """
    Verify that decision_hash matches committed decision fields.

    Returns:
    - ok
    - expected hash
    - actual hash
    """
    expected = sha256_json(committed_decision_payload(receipt))
    actual = receipt.get("decision_hash", "")
    return expected == actual, expected, actual


def verify_signature(receipt: Dict[str, Any]) -> Tuple[bool, str, str]:
    """
    Verify demo HMAC signature.

    Returns:
    - ok
    - expected signature
    - actual signature
    """
    payload = unsigned_receipt_payload(receipt)
    expected = demo_signature(canonical_json(payload))
    actual = receipt.get("signature", "")
    return hmac.compare_digest(expected, actual), expected, actual


def verify_receipt(path: Path) -> bool:
    """
    Verify a single receipt and print a human-readable report.

    Returns True if structural verification passes.
    """
    print("=" * 72)
    print(f"Verifying receipt: {path}")
    print("=" * 72)

    try:
        receipt = load_json(path)
    except ValueError as exc:
        print(f"FAIL: {exc}")
        return False

    missing = check_required_fields(receipt)
    if missing:
        print("FAIL: required fields are missing.")
        for field in missing:
            print(f"- missing: {field}")
        return False

    if receipt["receipt_type"] != RECEIPT_TYPE:
        print("FAIL: unexpected receipt_type.")
        print(f"Expected: {RECEIPT_TYPE}")
        print(f"Actual:   {receipt['receipt_type']}")
        return False

    hash_ok, expected_hash, actual_hash = verify_decision_hash(receipt)
    if not hash_ok:
        print("FAIL: decision_hash mismatch.")
        print(f"Expected: {expected_hash}")
        print(f"Actual:   {actual_hash}")
        return False

    sig_ok, expected_sig, actual_sig = verify_signature(receipt)
    if not sig_ok:
        print("FAIL: demo signature mismatch.")
        print(f"Expected: {expected_sig}")
        print(f"Actual:   {actual_sig}")
        return False

    print("PASS: receipt is structurally valid.")
    print(f"Decision ID:   {receipt['decision_id']}")
    print(f"Receipt label: {receipt['receipt_label']}")
    print(f"Issued at:     {receipt['issued_at']}")
    print(f"Decision hash: {receipt['decision_hash']}")
    print()

    print("Important limits:")
    print("- This verifies the structure of the receipt.")
    print("- This fixes the contestable decision object.")
    print("- This does not prove fairness, legality, truth, or correctness.")
    print("- This does not prove that the input was true.")
    print("- This does not prove that the explanation is valid.")
    print()

    print("Explanation hash semantics:")
    print("- explanation_hash fixes the operator's explanation at decision time.")
    print("- It does not validate that explanation.")
    print("- A sealed explanation is still only a sealed explanation.")

    return True


def compare_receipts(citizen_path: Path, operator_path: Path) -> bool:
    """
    Compare two receipts to detect split-view conflicts.

    Returns True if no conflict is found.
    Returns False if a conflict is detected.
    """
    print("=" * 72)
    print("Split-view comparison")
    print("=" * 72)

    try:
        citizen = load_json(citizen_path)
        operator = load_json(operator_path)
    except ValueError as exc:
        print(f"FAIL: {exc}")
        return False

    citizen_missing = check_required_fields(citizen)
    operator_missing = check_required_fields(operator)

    if citizen_missing or operator_missing:
        print("FAIL: one or both receipts are missing required fields.")
        if citizen_missing:
            print("Citizen receipt missing:")
            for field in citizen_missing:
                print(f"- {field}")
        if operator_missing:
            print("Operator receipt missing:")
            for field in operator_missing:
                print(f"- {field}")
        return False

    citizen_id = citizen["decision_id"]
    operator_id = operator["decision_id"]

    print(f"Citizen decision_id: {citizen_id}")
    print(f"Operator decision_id: {operator_id}")

    if citizen_id != operator_id:
        print()
        print("PASS: receipts refer to different decision_id values.")
        print("No split-view conflict for the same decision_id was detected.")
        return True

    citizen_hash = citizen["decision_hash"]
    operator_hash = operator["decision_hash"]

    print(f"Citizen decision_hash: {citizen_hash}")
    print(f"Operator decision_hash: {operator_hash}")

    if citizen_hash == operator_hash:
        print()
        print("PASS: same decision_id and same decision_hash.")
        print("No split-view conflict detected.")
        return True

    print()
    print("FAIL: conflicting receipts detected for the same decision_id.")
    print("Meaning:")
    print("- The citizen-held receipt and operator-held receipt cannot both be")
    print("  the same committed decision object.")
    print("- This exposes retroactive inconsistency or split-view reconstruction.")
    print()
    print("Important limit:")
    print("- This does not prove the citizen wins on the merits.")
    print("- It proves that the object of contestation is inconsistent.")

    return False


def verify_non_issuance(expected_receipt_path: Path) -> bool:
    """
    Demonstrate non-issuance as a process failure.

    This does not prove unfairness.
    It only shows that the contestability object is missing.
    """
    print("=" * 72)
    print("Non-issuance check")
    print("=" * 72)

    if expected_receipt_path.exists():
        print("PASS: expected receipt exists.")
        print(f"Receipt path: {expected_receipt_path}")
        return True

    print("FAIL: no decision receipt was issued.")
    print("Meaning: contestability object missing.")
    print("This does not prove unfairness, illegality, truth, or correctness.")
    print()
    print("Institutional implication:")
    print("- If a system is required to issue a receipt and fails to do so,")
    print("  that absence should be treated as a process failure.")
    print("- This PoC cannot force issuance. That requires law, policy,")
    print("  procurement rules, regulation, or institutional adoption.")

    return False


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Verify A-DAP Decision Receipt PoC receipts."
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    verify_parser = subparsers.add_parser(
        "verify",
        help="Verify a single receipt.",
    )
    verify_parser.add_argument(
        "receipt",
        help="Path to receipt JSON.",
    )

    compare_parser = subparsers.add_parser(
        "compare",
        help="Compare citizen-held and operator-held receipts for split-view conflict.",
    )
    compare_parser.add_argument(
        "citizen_receipt",
        help="Path to citizen-held receipt JSON.",
    )
    compare_parser.add_argument(
        "operator_receipt",
        help="Path to operator-held receipt JSON.",
    )

    non_issuance_parser = subparsers.add_parser(
        "non-issuance",
        help="Check whether an expected receipt exists.",
    )
    non_issuance_parser.add_argument(
        "expected_receipt",
        help="Path where the receipt should exist.",
    )

    args = parser.parse_args()

    if args.command == "verify":
        ok = verify_receipt(Path(args.receipt))
    elif args.command == "compare":
        ok = compare_receipts(
            Path(args.citizen_receipt),
            Path(args.operator_receipt),
        )
    elif args.command == "non-issuance":
        ok = verify_non_issuance(Path(args.expected_receipt))
    else:
        print("Unknown command.")
        ok = False

    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
